import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {encodeCBOR} from '@levischuck/tiny-cbor';
import {provisionOwner,OWNER_EMAIL} from '../server/owner-bootstrap.js';import {visibleGuide,answerSite} from '../server/site-guide.js';import '../public/js/vision-model.js';
const testDir=fs.mkdtempSync(path.join(os.tmpdir(),'rasid-passkey-test-'));process.env.RASID_DATA_DIR=testDir;const {hashPin,checkPin}=await import('../server/auth.js');
const V=globalThis.VisionModel;
test('Owner bootstrap requires a deployment secret, restores only owner and preserves a later PIN change',()=>{const db={users:{},settings:{},sessions:{}};assert.equal(provisionOwner(db,{}),false);const hash=hashPin('654321'),env={RASID_OWNER_PIN_HASH:hash};assert.equal(provisionOwner(db,env),true);assert.equal(db.users[OWNER_EMAIL].role,'admin');assert.ok(checkPin('654321',db.users[OWNER_EMAIL].pinHash));db.users.other={role:'student'};db.users[OWNER_EMAIL].pinHash=hashPin('456789');assert.equal(provisionOwner(db,env),false);assert.ok(checkPin('456789',db.users[OWNER_EMAIL].pinHash));db.users[OWNER_EMAIL].role='student';provisionOwner(db,env);assert.equal(db.users[OWNER_EMAIL].role,'admin');assert.equal(db.users.other.role,'student');assert.throws(()=>provisionOwner(db,{RASID_OWNER_PIN_HASH:'bad'}));});
test('Vision evaluates real pixel transforms, threshold tradeoffs and distinct security checks',()=>{const safe={threshold:.8,liveness:true,badge:true,hours:true},results=V.samples.map(s=>V.decide(s,safe));assert.equal(results[1],'deny');assert.equal(results[2],'deny');assert.equal(results[4],'deny');assert.deepEqual(V.evaluate(results),{tp:2,fp:0,tn:5,fn:1,accuracy:.875});assert.equal(V.evaluate(V.samples.map(s=>V.decide(s,{...safe,threshold:.3,liveness:false,badge:false,hours:false}))).fp,5);const flat=new Uint8ClampedArray(4*9).fill(100);assert.equal(V.pixels(flat,3,3,'edges')[4],0);assert.equal(V.pixels(flat,3,3,'threshold',99)[4],255);assert.equal(V.pixels(flat,3,3,'gray')[4],100);});
test('Site guide provides allowlisted navigation and respects roles and subjects',()=>{const u={role:'student',subject:'ai'};assert.ok(!visibleGuide(u).some(d=>d.view==='people'));assert.equal(answerSite('open computer vision workshop',u).cards[0].view,'vision');assert.equal(answerSite('كيف أضيف بصمة',u,'ar').cards[0].view,'settings');assert.ok(!visibleGuide({role:'teacher',subject:'math'}).some(d=>d.view==='vision'));});
test('Passkeys verify real signed assertions, isolate login attempts and reject replay/origin mismatch',async()=>{
 const {load,saveNow}=await import('../server/db.js');const auth=await import('../server/auth.js');const db=load(),email='passkey@example.test';const u=db.users[email]={email,role:'student',passkeys:[]};const req={headers:{host:'localhost:3218'},cookies:{rasid:'test-session'},secure:false};const oldOrigin=process.env.PUBLIC_ORIGIN;delete process.env.PUBLIC_ORIGIN;delete process.env.RENDER_EXTERNAL_URL;
 try{const opts=await auth.passkeyRegisterOptions(req,u);assert.equal(opts.authenticatorSelection.userVerification,'required');assert.equal(opts.authenticatorSelection.residentKey,'required');const pair=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'}),jwk=pair.publicKey.export({format:'jwk'}),cid=crypto.randomBytes(32),cose=encodeCBOR(new Map([[1,2],[3,-7],[-1,1],[-2,new Uint8Array(Buffer.from(jwk.x,'base64url'))],[-3,new Uint8Array(Buffer.from(jwk.y,'base64url'))]]));const rpHash=crypto.createHash('sha256').update('localhost').digest(),len=Buffer.alloc(2);len.writeUInt16BE(cid.length);const authData=Buffer.concat([rpHash,Buffer.from([0x45]),Buffer.alloc(4),Buffer.alloc(16),len,cid,Buffer.from(cose)]);const client=Buffer.from(JSON.stringify({type:'webauthn.create',challenge:opts.challenge,origin:'http://localhost:3218'}));const response={id:cid.toString('base64url'),rawId:cid.toString('base64url'),type:'public-key',clientExtensionResults:{},response:{clientDataJSON:client.toString('base64url'),attestationObject:Buffer.from(encodeCBOR(new Map([['fmt','none'],['attStmt',new Map()],['authData',new Uint8Array(authData)]]))).toString('base64url'),transports:['internal']}};
 assert.equal(await auth.passkeyRegisterVerify(req,u,response),true);assert.equal(u.passkeys.length,1);await assert.rejects(()=>auth.passkeyRegisterVerify(req,u,response));
 const a=await auth.passkeyLoginOptions(req,email),b=await auth.passkeyLoginOptions(req,email);assert.notEqual(a.ticket,b.ticket);
 const assertion=(opts,origin='http://localhost:3218')=>{const client=Buffer.from(JSON.stringify({type:'webauthn.get',challenge:opts.challenge,origin})),counter=Buffer.alloc(4);counter.writeUInt32BE(1);const data=Buffer.concat([rpHash,Buffer.from([5]),counter]),sig=crypto.sign('sha256',Buffer.concat([data,crypto.createHash('sha256').update(client).digest()]),pair.privateKey);return{id:cid.toString('base64url'),rawId:cid.toString('base64url'),type:'public-key',clientExtensionResults:{},response:{clientDataJSON:client.toString('base64url'),authenticatorData:data.toString('base64url'),signature:sig.toString('base64url')}};};
 assert.equal((await auth.passkeyLoginVerify(req,email,assertion(a),a.ticket)).email,email);await assert.rejects(()=>auth.passkeyLoginVerify(req,email,assertion(a),a.ticket));await assert.rejects(()=>auth.passkeyLoginVerify(req,email,assertion(b,'https://impostor.invalid'),b.ticket));
 }finally{if(oldOrigin===undefined)delete process.env.PUBLIC_ORIGIN;else process.env.PUBLIC_ORIGIN=oldOrigin;saveNow();}
});
