import {initialize,id,now} from './memory.js';
export const projectTypes=[['rag','RAG assistant','مساعد RAG'],['support','Customer-support agent','وكيل خدمة العملاء'],['recommendation','Recommendation system','نظام توصيات'],['documents','Document Q&A','أسئلة وأجوبة المستندات'],['research','Research assistant','مساعد بحث'],['classifier','Image classifier','مصنف صور'],['automation','Workflow automation','أتمتة سير العمل'],['multiagent','Multi-agent application','تطبيق متعدد الوكلاء']];
const STEPS=[['Define the user and success test','حدد المستخدم واختبار النجاح','Write one user need, three sample inputs and measurable acceptance criteria.','اكتب حاجة مستخدم واحدة وثلاثة مدخلات تجريبية ومعايير نجاح قابلة للقياس.'],['Prepare knowledge and data','جهز المعرفة والبيانات','Choose permitted data, inspect quality, and keep private information out of your test set.','اختر بيانات مسموحة وافحص جودتها وأبعد المعلومات الخاصة عن مجموعة الاختبار.'],['Build the smallest working flow','ابن أصغر تدفق يعمل','Sketch input → retrieval/model → output. Implement one path before adding tools.','ارسم المدخلات ← الاسترجاع أو النموذج ← المخرجات. نفذ مساراً واحداً قبل إضافة الأدوات.'],['Evaluate and handle failures','قيّم النظام وعالج الإخفاقات','Run your three cases and an adversarial input in your own safe development environment. Record expected versus actual output.','اختبر الحالات الثلاث ومدخلاً مضللاً في بيئة تطوير آمنة لديك. سجل النتائج المتوقعة والفعلية.'],['Improve and explain your decisions','حسّن واشرح قراراتك','Document limitations, cost, latency and privacy. Explain one trade-off and the next improvement.','وثق القيود والتكلفة وزمن الاستجابة والخصوصية. اشرح مفاضلة واحدة والتحسين التالي.']];
const BUILD={
 rag:['Chunk documents, retrieve relevant passages, and answer with source references. Start with three documents.','قسّم المستندات إلى مقاطع، واسترجع المقاطع المناسبة، وأجب مع المصادر. ابدأ بثلاثة مستندات.'],
 support:['Classify a support request, retrieve a verified policy, and escalate when the policy does not answer it.','صنّف طلب الدعم واسترجع سياسة موثوقة وصعّد الطلب عندما لا تجيب السياسة عنه.'],
 recommendation:['Build a simple popularity baseline, then compare a content-based recommendation on held-out examples.','ابن خط أساس بحسب الشعبية ثم قارنه بتوصيات تعتمد على المحتوى في أمثلة محفوظة للاختبار.'],
 documents:['Extract document text, preserve page references and return a supported answer or an explicit unknown.','استخرج نص المستند مع أرقام الصفحات وأعد إجابة مدعومة أو صرّح بعدم المعرفة.'],
 research:['Search an approved source list, deduplicate reports, and show dates and citations with each claim.','ابحث في مصادر معتمدة وأزل الأخبار المتكررة وأظهر التواريخ والمراجع مع كل ادعاء.'],
 classifier:['Separate training and test images before fitting a baseline; inspect a confusion matrix and class imbalance.','افصل صور التدريب والاختبار قبل تدريب خط أساس، وافحص مصفوفة الالتباس وعدم توازن الفئات.'],
 automation:['Map trigger, validated input, action and approval. Build a dry-run before allowing external writes.','حدد المحفز والمدخلات المتحقق منها والإجراء والموافقة. ابن تجربة محاكاة قبل السماح بالكتابة الخارجية.'],
 multiagent:['Route between two narrowly scoped roles. Define typed messages, tool permissions and a stopping condition.','وجّه الطلبات بين دورين محدودين. حدد بنية الرسائل وصلاحيات الأدوات وشرط التوقف.']};
export function createProject(db,user,type,lang){const template=projectTypes.find(x=>x[0]===type);if(!template)throw new Error('unknown_project');const a=initialize(db);a.projects[user.email]||=[];if(a.projects[user.email].length>=8)throw new Error('project_limit');const p={id:id(),type,title:template[lang==='ar'?2:1],createdAt:now(),updatedAt:now(),milestones:STEPS.map((s,i)=>({id:String(i+1),title:s[lang==='ar'?1:0],brief:i===2?BUILD[type][lang==='ar'?1:0]:s[lang==='ar'?3:2],submission:'',completed:false,review:null}))};a.projects[user.email].push(p);return p;}
export function projectFor(db,user,projectId){return initialize(db).projects[user.email]?.find(p=>p.id===projectId);}
export function updateMilestone(db,user,projectId,milestoneId,submission,completed){const p=projectFor(db,user,projectId),m=p?.milestones.find(x=>x.id===milestoneId);if(!m)throw new Error('project_not_found');if(typeof submission!=='string'||submission.length>8000||typeof completed!=='boolean')throw new Error('invalid_submission');m.submission=submission;m.completed=completed;m.updatedAt=now();p.updatedAt=now();return p;}

export function localizeProject(p,lang){const ar=lang==='ar';return {...p,title:projectTypes.find(t=>t[0]===p.type)?.[ar?2:1]||p.title,milestones:p.milestones.map((m,i)=>({...m,title:STEPS[i]?.[ar?1:0]||m.title,brief:i===2?BUILD[p.type]?.[ar?1:0]||m.brief:STEPS[i]?.[ar?3:2]||m.brief}))};}
