// Builds the files needed to run Rasid without a server (GitHub Pages / demo mode):
//  - public/js/curriculum-data.js  (the whole course as a browser global)
//  - public/vendor/webauthn.js     (copied from node_modules so the page loads without Express)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import beginner from "../data/curriculum/beginner.js";
import intermediate from "../data/curriculum/intermediate.js";
import expert from "../data/curriculum/expert.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");
const out = path.join(root, "public", "js", "curriculum-data.js");
fs.writeFileSync(out, `// Generated by scripts/build-static.js. Edit data/curriculum/*.js instead.\nwindow.CURRICULUM = ${JSON.stringify({ beginner, intermediate, expert })};\n`);
fs.mkdirSync(path.join(root, "public", "vendor"), { recursive: true });
fs.copyFileSync(path.join(root, "node_modules/@simplewebauthn/browser/dist/bundle/index.umd.min.js"), path.join(root, "public", "vendor", "webauthn.js"));
console.log("static build written:", path.relative(root, out), `(${Math.round(fs.statSync(out).size / 1024)} KB)`);

fs.copyFileSync(path.join(root, "node_modules/gsap/dist/gsap.min.js"), path.join(root, "public/vendor/gsap.min.js"));

const {build}=await import("esbuild");
await build({entryPoints:[path.join(root,"scripts/local-tutor-worker.js")],outfile:path.join(root,"public/vendor/local-tutor-worker.js"),bundle:true,format:"esm",platform:"browser",minify:true});

await import("./build-guide.js");
