import PDFDocument from 'pdfkit';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {SITE_GUIDE,GUIDE_VERSION} from '../data/knowledge/site-guide.js';
const out=new URL('../public/guides/',import.meta.url);fs.mkdirSync(out,{recursive:true});
const revision=crypto.createHash('sha256').update(JSON.stringify(SITE_GUIDE)).digest('hex').slice(0,12);
const doc=new PDFDocument({size:'A4',margin:50,bufferPages:true,info:{Title:'Rasid AI - Site Guide',Author:'Rasid AI',Subject:'Versioned platform knowledge and navigation'}});const stream=fs.createWriteStream(new URL('rasid-site-guide.pdf',out));doc.pipe(stream);
const text=s=>s.replace(/[→←]/g,' / ').replace(/[–—]/g,'-');
doc.rect(0,0,595,180).fill('#153e46');doc.fillColor('#a6e7d6').font('Helvetica-Bold').fontSize(12).text('RASID AI  /  LEARN. BUILD. UNDERSTAND.',50,45);doc.fillColor('#ffffff').fontSize(31).text('Your platform guide',50,80);doc.font('Helvetica').fontSize(12).text(`Knowledge version ${GUIDE_VERSION}  |  ${revision}`,50,127);doc.y=210;doc.fillColor('#193b43').fontSize(13).text('One source for the site guide, chatbot answers and this PDF. Generated automatically during each build. This document describes features, not private account records or live booking availability.',{lineGap:5});doc.moveDown();doc.fontSize(11).fillColor('#53636b').text('Use the bilingual in-app Site guide & PDF page to search and open sections. This downloadable edition is in English. Interface access is controlled by your signed-in role.');doc.moveDown(2);
for(const [i,s]of SITE_GUIDE.entries()){const title=`${String(i+1).padStart(2,'0')}  ${s.title.en}`,body=text(s.body.en);const h=doc.font('Helvetica').fontSize(10.5).heightOfString(body,{width:495,lineGap:3})+83;if(doc.y+h>765)doc.addPage();doc.font('Helvetica-Bold').fontSize(15).fillColor('#165e58').text(title);doc.moveDown(.35);doc.font('Helvetica').fontSize(9).fillColor('#6a727a').text(`SECTION: ${s.view.toUpperCase()}  |  ROLES: ${s.roles.join(', ')}${s.ai?'  |  AI subject access':''}`);doc.moveDown(.45);doc.fontSize(10.5).fillColor('#233640').text(body,{lineGap:3});doc.moveDown(1.2);}
if(doc.y>610)doc.addPage();doc.font('Helvetica-Bold').fontSize(13).fillColor('#165e58').text('Verification and scope');doc.moveDown(.5);doc.font('Helvetica').fontSize(10).fillColor('#233640').text('Passkeys use your device authenticator. The vision lab is a simulator and isolated client-side code runner. The free device tutor is optional and its quality varies. The PDF is rebuilt from data/knowledge/site-guide.js: changes to this source update both retrieval and the document in the same release.',{lineGap:3});doc.moveDown();doc.fillColor('#165e58').text('Passkey documentation: simplewebauthn.dev/docs',{link:'https://simplewebauthn.dev/docs'});doc.text('Android passkeys: passkeys.dev/docs/reference/android/',{link:'https://passkeys.dev/docs/reference/android/'});
const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(i);doc.save();doc.moveTo(50,787).lineTo(545,787).strokeColor('#d8e2dd').stroke();doc.font('Helvetica').fontSize(8).fillColor('#62756f').text(`RASID AI  |  ${revision}`,50,798,{lineBreak:false});doc.text(`${i+1} / ${range.count}`,490,798,{lineBreak:false});doc.restore();}
doc.end();await new Promise((resolve,reject)=>{stream.on('finish',resolve);stream.on('error',reject);});fs.writeFileSync(new URL('manifest.json',out),JSON.stringify({version:GUIDE_VERSION,revision,sections:SITE_GUIDE.length}));console.log('Site guide PDF built: '+range.count+' pages, revision '+revision);
